#!/usr/bin/env python3
"""Fill en.json with short English Zi Wei terms (not Hanyu pinyin)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "tuvi_mcp" / "i18n" / "en.json"

UPDATES = {
    "ui": {
        "LÁ SỐ TỬ VI": "HOROSCOPE CHART",
        "Khách": "Guest",
        "month_pattern": "Mo. {n}",
        " · THÂN": " · BODY",
        "Tuần": "Gap",
        "Triệt": "Cut",
        "N/A": "N/A",
        "Dương lịch": "Solar",
        "Âm lịch": "Lunar",
        "Giờ sinh": "Hour",
        "Năm sinh": "Year",
        "Âm dương": "YinYang",
        "Bản mệnh": "Nature",
        "Hành cục": "Phase",
        "Chủ mệnh": "Life star",
        "Chủ thân": "Body star",
        "Năm xem": "View year",
    },
    "can": {
        "Giáp": "Jia",
        "Ất": "Yi",
        "Bính": "Bing",
        "Đinh": "Ding",
        "Mậu": "Wu",
        "Kỷ": "Ji",
        "Canh": "Geng",
        "Tân": "Xin",
        "Nhâm": "Ren",
        "Quý": "Gui",
    },
    "chi": {
        "Tý": "Rat",
        "Tí": "Rat",
        "Sửu": "Ox",
        "Dần": "Tiger",
        "Mão": "Rabbit",
        "Mẹo": "Rabbit",
        "Thìn": "Dragon",
        "Tỵ": "Snake",
        "Tị": "Snake",
        "Ngọ": "Horse",
        "Mùi": "Goat",
        "Thân": "Monkey",
        "Dậu": "Rooster",
        "Tuất": "Dog",
        "Hợi": "Pig",
    },
    "can_abbr": {
        "Giáp": "Jia.",
        "Ất": "Yi.",
        "Bính": "Bing.",
        "Đinh": "Ding.",
        "Mậu": "Wu.",
        "Kỷ": "Ji.",
        "Canh": "Geng.",
        "Tân": "Xin.",
        "Nhâm": "Ren.",
        "Quý": "Gui.",
    },
    "palaces": {
        "Mệnh": "Life",
        "Phụ mẫu": "Parents",
        "Phúc đức": "Fortune",
        "Điền trạch": "Property",
        "Quan lộc": "Career",
        "Nô bộc": "Friends",
        "Thiên di": "Travel",
        "Tật ách": "Health",
        "Tài bạch": "Wealth",
        "Tử tức": "Children",
        "Phu thê": "Spouse",
        "Huynh đệ": "Siblings",
    },
    "elements": {
        "Kim": "Metal",
        "Mộc": "Wood",
        "Thủy": "Water",
        "Hỏa": "Fire",
        "Thổ": "Earth",
    },
    "stars": {
        "Tử vi": "Emperor",
        "Liêm trinh": "Virtue",
        "Thiên đồng": "Lucky",
        "Vũ khúc": "Marshal",
        "Thái Dương": "Sun",
        "Thiên cơ": "Advisor",
        "Thiên phủ": "Treasury",
        "Thái âm": "Moon",
        "Tham lang": "Wolf",
        "Cự môn": "Gate",
        "Thiên tướng": "Minister",
        "Thiên lương": "Elder",
        "Thất sát": "Killer",
        "Phá quân": "Ruin",
        "Thái tuế": "Year",
        "Thiếu dương": "Jr Yang",
        "Tang môn": "Grief",
        "Thiếu âm": "Jr Yin",
        "Quan phù": "Officer",
        "Tử phù": "Death F.",
        "Tuế phá": "Breaker",
        "Long đức": "Dragon",
        "Bạch hổ": "White T.",
        "Phúc đức": "Blessing",
        "Điếu khách": "Mourner",
        "Trực phù": "Duty",
        "Lộc tồn": "Salary",
        "Bác sỹ": "Scholar",
        "Lực sĩ": "Guard",
        "Thanh long": "Azure",
        "Tiểu hao": "Loss-",
        "Tướng quân": "General",
        "Tấu thư": "Letter",
        "Phi liêm": "Gale",
        "Hỷ thần": "Joy",
        "Bệnh phù": "Illness",
        "Đại hao": "Loss+",
        "Phục binh": "Ambush",
        "Tràng sinh": "Birth",
        "Mộc dục": "Bath",
        "Quan đới": "Crown",
        "Lâm quan": "Office",
        "Đế vượng": "Peak",
        "Suy": "Decline",
        "Bệnh": "Sick",
        "Tử": "Death",
        "Mộ": "Grave",
        "Tuyệt": "Void",
        "Thai": "Womb",
        "Dưỡng": "Nourish",
        "Đà la": "Spinner",
        "Kình dương": "Ram",
        "Địa không": "Empty",
        "Địa kiếp": "Calamity",
        "Linh tinh": "Bell",
        "Hỏa tinh": "Spark",
        "Văn xương": "Writer",
        "Văn Khúc": "Artist",
        "Thiên khôi": "Aide+",
        "Thiên việt": "Aide-",
        "Tả phù": "Left Aid",
        "Hữu bật": "Right Aid",
        "Long trì": "Pool",
        "Phượng các": "Phoenix",
        "Tam thai": "Trio",
        "Bát tọa": "Seat",
        "Ân quang": "Grace",
        "Thiên quý": "Noble",
        "Thiên khốc": "Weep",
        "Thiên hư": "Hollow",
        "Thiên đức": "Sky De",
        "Nguyệt đức": "Moon De",
        "Thiên hình": "Penalty",
        "Thiên riêu": "Charm",
        "Thiên y": "Doctor",
        "Quốc ấn": "Seal",
        "Đường phù": "Hall",
        "Đào hoa": "Peach",
        "Hồng loan": "Swan",
        "Thiên hỷ": "Glee",
        "Thiên giải": "Relief",
        "Địa giải": "Absolve",
        "Giải thần": "Pardon",
        "Thai phụ": "Aide",
        "Phong cáo": "Decree",
        "Thiên tài": "Talent",
        "Thiên thọ": "Longevity",
        "Thiên thương": "Wound",
        "Thiên sứ": "Angel",
        "Thiên la": "Sky Net",
        "Địa võng": "Earth Net",
        "Hóa khoa": "Fame",
        "Hóa quyền": "Power",
        "Hóa lộc": "Lucre",
        "Hóa kỵ": "Taboo",
        "Cô thần": "Orphan",
        "Quả tú": "Widow",
        "Thiên mã": "Steed",
        "Phá toái": "Shatter",
        "Thiên quan": "Rank",
        "Thiên phúc": "Bounty",
        "Lưu hà": "Haze",
        "Thiên trù": "Kitchen",
        "Kiếp sát": "Raid",
        "Hoa cái": "Canopy",
        "LN. Văn tinh": "Yr Lit.",
        "Đẩu quân": "Dipper",
        "Thiên không": "Sky Gap",
        "Văn khúc": "Artist",
        "HẢI TRUNG KIM": "Sea Gold",
        "GIÁNG HẠ THỦY": "Stream Water",
        "TÍCH LỊCH HỎA": "Thunder Fire",
        "BÍCH THƯỢNG THỔ": "Wall Earth",
        "TANG ÐỐ MỘC": "Mulberry",
        "ÐẠI KHÊ THỦY": "Creek Water",
        "LƯ TRUNG HỎA": "Furnace Fire",
        "THÀNH ÐẦU THỔ": "City Earth",
        "TÒNG BÁ MỘC": "Pine Wood",
        "KIM BẠCH KIM": "White Gold",
        "PHÚ ÐĂNG HỎA": "Lamp Fire",
        "SA TRUNG THỔ": "Sand Earth",
        "ÐẠI LÂM MỘC": "Forest Wood",
        "BẠCH LẠP KIM": "Wax Gold",
        "TRƯỜNG LƯU THỦY": "Long Stream",
        "SA TRUNG KIM": "Sand Gold",
        "THIÊN HÀ THỦY": "Sky River",
        "THIÊN THƯỢNG HỎA": "Sky Fire",
        "LỘ BÀN THỔ": "Road Earth",
        "DƯƠNG LIỄU MỘC": "Willow",
        "TRUYỀN TRUNG THỦY": "Spring Water",
        "SƠN HẠ HỎA": "Hill Fire",
        "ÐẠI TRẠCH THỔ": "Marsh Earth",
        "THẠCH LỰU MỘC": "Pomegr.",
        "KIẾM PHONG KIM": "Sword Gold",
        "SƠN ÐẦU HỎA": "Peak Fire",
        "ỐC THƯỢNG THỔ": "Roof Earth",
        "BÌNH ÐỊA MỘC": "Plain Wood",
        "XOA XUYẾN KIM": "Pin Gold",
        "ÐẠI HẢI THỦY": "Ocean Water",
        "Kim tứ Cục": "Metal 4",
        "Mộc tam Cục": "Wood 3",
        "Thủy nhị Cục": "Water 2",
        "Hỏa lục Cục": "Fire 6",
        "Thổ ngũ Cục": "Earth 5",
        "Miếu": "Temple",
        "Vượng": "Prosper",
        "Đắc": "Gain",
        "Bình": "Neutral",
        "Hãm": "Fall",
        "L.Thái Tuế": "L.Year",
        "L.Lộc Tồn": "L.Salary",
        "L.Kình Dương": "L.Ram",
        "L.Đà La": "L.Spinner",
        "L.Thiên Mã": "L.Steed",
        "L.Thiên Khốc": "L.Weep",
        "L.Thiên Hư": "L.Hollow",
    },
    "brightness_abbrev": {
        "Miếu địa": "M",
        "Vượng địa": "V",
        "Đắc địa": "Đ",
        "Bình hòa": "B",
        "Hãm địa": "H",
        "M": "M",
        "V": "V",
        "Đ": "Đ",
        "B": "B",
        "H": "H",
    },
    "gender": {
        "Nam": "Male",
        "Nữ": "Female",
    },
    "am_duong": {
        "Dương": "Yang",
        "Âm": "Yin",
    },
}


def main() -> None:
    data = json.loads(PATH.read_text(encoding="utf-8"))
    extra: list[str] = []
    for section, mapping in UPDATES.items():
        if section not in data:
            raise SystemExit(f"missing section {section}")
        extra.extend(f"{section}.{k}" for k in mapping if k not in data[section])
        leftover = [k for k in data[section] if k not in mapping]
        if leftover:
            raise SystemExit(f"unmapped {section} keys: {leftover}")
        for key, value in mapping.items():
            data[section][key] = value
    if extra:
        raise SystemExit(f"updates missing from catalog: {extra}")
    PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {PATH}")


if __name__ == "__main__":
    main()
