#!/usr/bin/env python3
"""Fill ms.json with short Malay Zi Wei terms (keys stay Vietnamese identity)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "tuvi_mcp" / "i18n" / "ms.json"

# Star/stem pinyin stays short (A1 Latin overflow). Overlay Malay chrome.
UPDATES = {
    "ui": {
        "LÁ SỐ TỬ VI": "CARTA ZIWEI",
        "Khách": "Tetamu",
        "month_pattern": "Bln {n}",
        " · THÂN": " · Badan",
        "Tuần": "Xun",
        "Triệt": "Jie",
        "N/A": "N/A",
        "Dương lịch": "Suria",
        "Âm lịch": "Qamari",
        "Giờ sinh": "Jam",
        "Năm sinh": "Tahun",
        "Âm dương": "YinYang",
        "Bản mệnh": "Nasib",
        "Hành cục": "Biro",
        "Chủ mệnh": "Btg Ming",
        "Chủ thân": "Btg Badan",
        "Năm xem": "Thn rujuk",
    },
    "can": {
        "Giáp": "Jia",
        "Ất": "Yi",
        "Bính": "Bing",
        "Đinh": "Ding",
        "Mậu": "Wu",
        "Kỷ": "Ji",
        "Canh": "Geng",
        "Tân": "Xin",
        "Nhâm": "Ren",
        "Quý": "Gui",
    },
    "chi": {
        "Tý": "Zi",
        "Tí": "Zi",
        "Sửu": "Chou",
        "Dần": "Yin",
        "Mão": "Mao",
        "Mẹo": "Mao",
        "Thìn": "Chen",
        "Tỵ": "Si",
        "Tị": "Si",
        "Ngọ": "Wu",
        "Mùi": "Wei",
        "Thân": "Shen",
        "Dậu": "You",
        "Tuất": "Xu",
        "Hợi": "Hai",
    },
    "can_abbr": {
        "Giáp": "Jia.",
        "Ất": "Yi.",
        "Bính": "Bing.",
        "Đinh": "Ding.",
        "Mậu": "Wu.",
        "Kỷ": "Ji.",
        "Canh": "Geng.",
        "Tân": "Xin.",
        "Nhâm": "Ren.",
        "Quý": "Gui.",
    },
    "palaces": {
        "Mệnh": "Ming",
        "Phụ mẫu": "Ibu",
        "Phúc đức": "Tuah",
        "Điền trạch": "Rumah",
        "Quan lộc": "Kerja",
        "Nô bộc": "Rakan",
        "Thiên di": "Rantau",
        "Tật ách": "Sihat",
        "Tài bạch": "Harta",
        "Tử tức": "Anak",
        "Phu thê": "Pasang",
        "Huynh đệ": "Adik",
    },
    "elements": {
        "Kim": "Logam",
        "Mộc": "Kayu",
        "Thủy": "Air",
        "Hỏa": "Api",
        "Thổ": "Tanah",
    },
    "stars": {
        "Tử vi": "Zi Wei",
        "Liêm trinh": "Lian Zhen",
        "Thiên đồng": "Tian Tong",
        "Vũ khúc": "Wu Qu",
        "Thái Dương": "Matahari",
        "Thiên cơ": "Tian Ji",
        "Thiên phủ": "Tian Fu",
        "Thái âm": "Bulan",
        "Tham lang": "Tan Lang",
        "Cự môn": "Ju Men",
        "Thiên tướng": "Tian Xiang",
        "Thiên lương": "Tian Liang",
        "Thất sát": "Qi Sha",
        "Phá quân": "Po Jun",
        "Thái tuế": "Tai Sui",
        "Thiếu dương": "Shao Yang",
        "Tang môn": "Sang Men",
        "Thiếu âm": "Shao Yin",
        "Quan phù": "Guan Fu",
        "Tử phù": "Si Fu",
        "Tuế phá": "Sui Po",
        "Long đức": "Long De",
        "Bạch hổ": "Bai Hu",
        "Phúc đức": "Fu De",
        "Điếu khách": "Diao Ke",
        "Trực phù": "Zhi Fu",
        "Lộc tồn": "Lu Cun",
        "Bác sỹ": "Bo Shi",
        "Lực sĩ": "Li Shi",
        "Thanh long": "Qing Long",
        "Tiểu hao": "Xiao Hao",
        "Tướng quân": "Jiang Jun",
        "Tấu thư": "Zou Shu",
        "Phi liêm": "Fei Lian",
        "Hỷ thần": "Xi Shen",
        "Bệnh phù": "Bing Fu",
        "Đại hao": "Da Hao",
        "Phục binh": "Fu Bing",
        "Tràng sinh": "Lahir",
        "Mộc dục": "Mandi",
        "Quan đới": "Mahkota",
        "Lâm quan": "Pejabat",
        "Đế vượng": "Puncak",
        "Suy": "Surut",
        "Bệnh": "Sakit",
        "Tử": "Mati",
        "Mộ": "Kubur",
        "Tuyệt": "Kosong",
        "Thai": "Rahim",
        "Dưỡng": "Asuh",
        "Đà la": "Tuo Luo",
        "Kình dương": "Qing Yang",
        "Địa không": "Di Kong",
        "Địa kiếp": "Di Jie",
        "Linh tinh": "Ling Xing",
        "Hỏa tinh": "Huo Xing",
        "Văn xương": "Wen Chang",
        "Văn Khúc": "Wen Qu",
        "Thiên khôi": "Tian Kui",
        "Thiên việt": "Tian Yue",
        "Tả phù": "Zuo Fu",
        "Hữu bật": "You Bi",
        "Long trì": "Long Chi",
        "Phượng các": "Feng Ge",
        "Tam thai": "San Tai",
        "Bát tọa": "Ba Zuo",
        "Ân quang": "En Guang",
        "Thiên quý": "Tian Gui",
        "Thiên khốc": "Tian Ku",
        "Thiên hư": "Tian Xu",
        "Thiên đức": "Tian De",
        "Nguyệt đức": "Yue De",
        "Thiên hình": "Tian Xing",
        "Thiên riêu": "Tian Yao",
        "Thiên y": "Tian Yi",
        "Quốc ấn": "Guo Yin",
        "Đường phù": "Tang Fu",
        "Đào hoa": "Tao Hua",
        "Hồng loan": "Hong Luan",
        "Thiên hỷ": "Tian Xi",
        "Thiên giải": "Tian Jie",
        "Địa giải": "Di Xie",
        "Giải thần": "Jie Shen",
        "Thai phụ": "Tai Fu",
        "Phong cáo": "Feng Gao",
        "Thiên tài": "Tian Cai",
        "Thiên thọ": "Tian Shou",
        "Thiên thương": "Tian Shang",
        "Thiên sứ": "Tian Shi",
        "Thiên la": "Tian Luo",
        "Địa võng": "Di Wang",
        "Hóa khoa": "Hua Ke",
        "Hóa quyền": "Hua Quan",
        "Hóa lộc": "Hua Lu",
        "Hóa kỵ": "Hua Ji",
        "Cô thần": "Gu Chen",
        "Quả tú": "Gua Su",
        "Thiên mã": "Tian Ma",
        "Phá toái": "Po Sui",
        "Thiên quan": "Tian Guan",
        "Thiên phúc": "Berkat",
        "Lưu hà": "Liu Xia",
        "Thiên trù": "Tian Chu",
        "Kiếp sát": "Jie Sha",
        "Hoa cái": "Hua Gai",
        "LN. Văn tinh": "LN. Wen",
        "Đẩu quân": "Dou Jun",
        "Thiên không": "Tian Kong",
        "Văn khúc": "Wen Qu",
        "HẢI TRUNG KIM": "Emas laut",
        "GIÁNG HẠ THỦY": "Air lurah",
        "TÍCH LỊCH HỎA": "Api guruh",
        "BÍCH THƯỢNG THỔ": "Tanah dinding",
        "TANG ÐỐ MỘC": "Mulberi",
        "ÐẠI KHÊ THỦY": "Air anak",
        "LƯ TRUNG HỎA": "Api relau",
        "THÀNH ÐẦU THỔ": "Tanah kota",
        "TÒNG BÁ MỘC": "Kayu pain",
        "KIM BẠCH KIM": "Emas putih",
        "PHÚ ÐĂNG HỎA": "Api lampu",
        "SA TRUNG THỔ": "Tanah pasir",
        "ÐẠI LÂM MỘC": "Kayu hutan",
        "BẠCH LẠP KIM": "Emas lilin",
        "TRƯỜNG LƯU THỦY": "Alir panjang",
        "SA TRUNG KIM": "Emas pasir",
        "THIÊN HÀ THỦY": "Air langit",
        "THIÊN THƯỢNG HỎA": "Api langit",
        "LỘ BÀN THỔ": "Tanah jalan",
        "DƯƠNG LIỄU MỘC": "Salix",
        "TRUYỀN TRUNG THỦY": "Mata air",
        "SƠN HẠ HỎA": "Api bukit",
        "ÐẠI TRẠCH THỔ": "Tanah paya",
        "THẠCH LỰU MỘC": "Delima",
        "KIẾM PHONG KIM": "Emas pedang",
        "SƠN ÐẦU HỎA": "Api puncak",
        "ỐC THƯỢNG THỔ": "Tanah atap",
        "BÌNH ÐỊA MỘC": "Kayu rata",
        "XOA XUYẾN KIM": "Emas pin",
        "ÐẠI HẢI THỦY": "Air laut",
        "Kim tứ Cục": "Logam 4",
        "Mộc tam Cục": "Kayu 3",
        "Thủy nhị Cục": "Air 2",
        "Hỏa lục Cục": "Api 6",
        "Thổ ngũ Cục": "Tanah 5",
        "Miếu": "Miao",
        "Vượng": "Wang",
        "Đắc": "De",
        "Bình": "Ping",
        "Hãm": "Xian",
        "L.Thái Tuế": "L.Tai Sui",
        "L.Lộc Tồn": "L.Lu Cun",
        "L.Kình Dương": "L.Qing Yang",
        "L.Đà La": "L.Tuo Luo",
        "L.Thiên Mã": "L.Tian Ma",
        "L.Thiên Khốc": "L.Tian Ku",
        "L.Thiên Hư": "L.Tian Xu",
    },
    "brightness_abbrev": {
        "Miếu địa": "M",
        "Vượng địa": "W",
        "Đắc địa": "D",
        "Bình hòa": "P",
        "Hãm địa": "X",
        "M": "M",
        "V": "W",
        "Đ": "D",
        "B": "P",
        "H": "X",
    },
    "gender": {
        "Nam": "Lelaki",
        "Nữ": "Wanita",
    },
    "am_duong": {
        "Dương": "Yang",
        "Âm": "Yin",
    },
}


def main() -> None:
    data = json.loads(PATH.read_text(encoding="utf-8"))
    extra: list[str] = []
    for section, mapping in UPDATES.items():
        if section not in data:
            raise SystemExit(f"missing section {section}")
        extra.extend(f"{section}.{k}" for k in mapping if k not in data[section])
        leftover = [k for k in data[section] if k not in mapping]
        if leftover:
            raise SystemExit(f"unmapped {section} keys: {leftover}")
        for key, value in mapping.items():
            data[section][key] = value
    if extra:
        raise SystemExit(f"updates missing from catalog: {extra}")
    PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {PATH}")


if __name__ == "__main__":
    main()
